[package]
name = "life-game-distribution"
version = "0.1.0"
authors = ["Daiju Nakayama <42.daiju@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8"
rand_pcg = "0.3"
tqdm = "0.3"
clap = { version = "3.1", features = ["derive"] }
